name: Generate Documentation

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
    tags:
      - 'v*'

# 添加权限配置
permissions:
  contents: write

jobs:
  godoc:
    name: Generate Go Docs
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: true

    - name: Install documentation tools
      run: |
        # 安装pkgsite工具，这是官方推荐的替代godoc的工具
        go install golang.org/x/pkgsite/cmd/pkgsite@latest
        # 确保go doc命令可用（这是Go内置的）
        go version

    - name: Generate documentation
      run: |
        mkdir -p docs/api
        # 使用内置的go doc命令生成文档
        go doc -all ./pkg/api > docs/api/api-reference.txt
        go doc -all ./pkg/request > docs/api/request-reference.txt
        go doc -all ./pkg/response > docs/api/response-reference.txt

    - name: Commit and push documentation
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        add: 'docs/api/*'
        message: 'docs: update API documentation' 