# Go Tests 工作流
# 
# 该工作流在每次代码提交时自动运行单元测试、代码覆盖率分析和代码检查
# 修改历史:
# - 2025-04-14: 修改为在所有分支的每次提交时都运行测试，添加Go 1.21支持

name: Go Tests

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.18', '1.19', '1.20', '1.21']
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: go test -v -race -cover -coverprofile=coverage.out ./...

    - name: Convert coverage to XML for reporting
      run: |
        go install github.com/axw/gocov/gocov@latest
        go install github.com/AlekSi/gocov-xml@latest
        gocov convert coverage.out | gocov-xml > coverage.xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        verbose: true
        flags: unittests,${{ matrix.go-version }}
        name: codecov-umbrella

    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m
        skip-pkg-cache: false
        skip-build-cache: false

    - name: Build
      run: go build -v ./...

  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    needs: test
    # 保持基准测试只在主分支上运行，避免在每个提交上消耗过多资源
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: true
    
    - name: Run benchmarks
      run: go test -bench=. -benchmem ./... 